[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
script = 'script'
solc_version = '0.8.24'
evm_version = 'paris'
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false
gas_reports = ['*']

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'thousands'
single_line_statement_blocks = 'single'
respect_doc_comments = true

[profile.ci]
fuzz_runs = 1000
invariant_runs = 256

[dependencies]
forge-std = "1.11.0"
openzeppelin-contracts = "5.4.0"
openzeppelin-contracts-upgradeable = "5.4.0"
