global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: "development"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["rwa-dev-node-exporter:9100"]
        labels:
          environment: "development"
          service_name: "node-exporter"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
